# Generated by Django 4.2 on 2023-04-07 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinemeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Собрание', 'verbose_name_plural': 'Собрания'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель собрания'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title_of_meeting',
            field=models.CharField(max_length=150, verbose_name='Название собрания'),
        ),
    ]
