# Generated by Django 4.2 on 2023-04-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemeet', '0002_alter_meeting_options_alter_meeting_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ending_date_time',
            field=models.DateTimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting_date_time',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='unique_meeting_name',
            field=models.TextField(blank=True, null=True, verbose_name='Уникальное название собрания'),
        ),
    ]
